export const supportedUiLocales = ['en', 'zh-TW'] as const
export type UiLocale = typeof supportedUiLocales[number]

const en = {
  'Ditto · Organise files': 'Ditto · Organise files',
  'Ditto · Code → Spec': 'Ditto · Code → Spec',
  'Skip to content': 'Skip to content',
  'Local review page': 'Local review page',
  'Synthetic demo · deterministic generator, no model calls': 'Synthetic demo · deterministic generator, no model calls',
  'Review a few. Ditto the rest.': 'Review a few. Ditto the rest.',
  '· Review a few. Ditto the rest.': '· Review a few. Ditto the rest.',
  'Choose samples': 'Choose samples',
  'Review': 'Review',
  'Preview all': 'Preview all',
  'Apply': 'Apply',
  'Discover': 'Discover',
  'Review 3 samples': 'Review 3 samples',
  'Preview everything': 'Preview everything',
  'Review the proposed file locations': 'Review the proposed file locations',
  'Check three representative files, then inspect the complete batch before any copies are created. Originals are never moved or changed.': 'Check three representative files, then inspect the complete batch before any copies are created. Originals are never moved or changed.',
  'Review digest': 'Review digest',
  'Local-only review': 'Local-only review',
  'This page talks only to the loopback service that opened it. It loads no remote scripts, fonts, or analytics.': 'This page talks only to the loopback service that opened it. It loads no remote scripts, fonts, or analytics.',
  'Representative samples': 'Representative samples',
  'Edit a proposed location if needed. Changes rebuild the whole preview before apply.': 'Edit a proposed location if needed. Changes rebuild the whole preview before apply.',
  'Three deterministic samples': 'Three deterministic samples',
  'Original file': 'Original file',
  'Organised location': 'Organised location',
  'A path relative to the output folder. The original file is never moved.': 'A path relative to the output folder. The original file is never moved.',
  'No files to organise in this folder': 'No files to organise in this folder',
  'Choose a source folder that contains files, then create a new preview.': 'Choose a source folder that contains files, then create a new preview.',
  'No files to show.': 'No files to show.',
  'files': 'files',
  'Update preview': 'Update preview',
  'No unsaved location changes': 'No unsaved location changes',
  'Unsaved location changes': 'Unsaved location changes',
  'This batch': 'This batch',
  'Source files': 'Source files',
  'Ready to copy': 'Ready to copy',
  'Need attention': 'Need attention',
  'Source folder': 'Source folder',
  'New output folder': 'New output folder',
  'Before creating copies': 'Before creating copies',
  'Only the reviewed destinations are created. Existing files are never overwritten.': 'Only the reviewed destinations are created. Existing files are never overwritten.',
  'Create organised copies': 'Create organised copies',
  'Full batch': 'Full batch',
  'Actual copy results': 'Actual copy results',
  'Saved recipes': 'Saved recipes',
  'Save this reviewed rule for another batch. Loading a recipe always creates a new preview.': 'Save this reviewed rule for another batch. Loading a recipe always creates a new preview.',
  'Recipe name': 'Recipe name',
  'Save recipe': 'Save recipe',
  'Waiting': 'Waiting',
  'Copying': 'Copying',
  'Copied': 'Copied',
  'Needs a fix': 'Needs a fix',
  'Failed': 'Failed',
  'Needs review': 'Needs review',
  'Unknown result': 'Unknown result',
  'Enter the organised location.': 'Enter the organised location.',
  'Use a path relative to the output folder.': 'Use a path relative to the output folder.',
  'The location cannot leave the output folder.': 'The location cannot leave the output folder.',
  'Updating…': 'Updating…',
  'Creating copies…': 'Creating copies…',
  'Saving…': 'Saving…',
  'Loading…': 'Loading…',
  'Code-to-spec workflow': 'Code-to-spec workflow',
  'Code → Markdown specifications': 'Code → Markdown specifications',
  'Calibrate three samples, then ditto the rest': 'Calibrate three samples, then ditto the rest',
  'Your source is never executed or modified. Every fact in a specification cites source lines; anything unsupported is collected under “Needs confirmation”.': 'Your source is never executed or modified. Every fact in a specification cites source lines; anything unsupported is collected under “Needs confirmation”.',
  'Three structurally different samples': 'Three structurally different samples',
  'Edit the Markdown and the batch instructions directly; updates change the review digest.': 'Edit the Markdown and the batch instructions directly; updates change the review digest.',
  'Samples approved — the full batch can be generated.': 'Samples approved — the full batch can be generated.',
  'Samples not approved yet — full batch locked.': 'Samples not approved yet — full batch locked.',
  'Batch instructions (optional)': 'Batch instructions (optional)',
  'For example: list inputs, outputs, and observable errors first; keep each bullet under 25 words.': 'For example: list inputs, outputs, and observable errors first; keep each bullet under 25 words.',
  'Instructions only guide the text of this batch. They cannot run code or commands.': 'Instructions only guide the text of this batch. They cannot run code or commands.',
  'Update samples': 'Update samples',
  'Approve the three samples': 'Approve the three samples',
  'Generate the full batch': 'Generate the full batch',
  'Full batch preview': 'Full batch preview',
  'Full batch preview (': 'Full batch preview (',
  'modules)': 'modules)',
  'modules': 'modules',
  'Per-item write results': 'Per-item write results',
  'This scan': 'This scan',
  'Modules discovered': 'Modules discovered',
  'Specifications generated': 'Specifications generated',
  'Need confirmation': 'Need confirmation',
  'Excluded': 'Excluded',
  'New specification output folder': 'New specification output folder',
  'Needs confirmation': 'Needs confirmation',
  'Nothing needs confirmation right now.': 'Nothing needs confirmation right now.',
  'Excluded from the scan': 'Excluded from the scan',
  'Nothing was excluded.': 'Nothing was excluded.',
  'Before writing': 'Before writing',
  'Only a complete preview whose samples are approved and whose source snapshot is unchanged can be written. Nothing is written before you press the button.': 'Only a complete preview whose samples are approved and whose source snapshot is unchanged can be written. Nothing is written before you press the button.',
  'Write the approved specifications': 'Write the approved specifications',
  'Sample · review': 'Sample · review',
  'Approved': 'Approved',
  'Ready to write': 'Ready to write',
  'Generated': 'Generated',
  'Written': 'Written',
  'Skipped': 'Skipped',
  'Rejected': 'Rejected',
  'Editable Markdown specification': 'Editable Markdown specification',
  'Markdown specification preview': 'Markdown specification preview',
  'Not generated yet.': 'Not generated yet.',
  'No evidence linked back to the source yet.': 'No evidence linked back to the source yet.',
  'Unsaved sample or instruction edits — update the samples first.': 'Unsaved sample or instruction edits — update the samples first.',
  'Updating samples…': 'Updating samples…',
  'Recording approval…': 'Recording approval…',
  'Generating the full batch…': 'Generating the full batch…',
  'Writing Markdown…': 'Writing Markdown…',
  'Sample': 'Sample',
  'Edit, then press “Update samples”. Every change produces a new review digest.': 'Edit, then press “Update samples”. Every change produces a new review digest.',
  'Source evidence': 'Source evidence',
  'No modules available as samples.': 'No modules available as samples.',
  'No modules discovered.': 'No modules discovered.',
  'The scan did not report exclusion details.': 'The scan did not report exclusion details.',
  'Samples updated. Review and approve the three specifications again.': 'Samples updated. Review and approve the three specifications again.',
  'Update the samples before approving them.': 'Update the samples before approving them.',
  'Three samples approved. You can generate the full batch now.': 'Three samples approved. You can generate the full batch now.',
  'The local service did not confirm the approval.': 'The local service did not confirm the approval.',
  'Full batch generated. Resolve anything under “Needs confirmation”, then write the specifications.': 'Full batch generated. Resolve anything under “Needs confirmation”, then write the specifications.',
  'Write complete. Per-item results are listed below.': 'Write complete. Per-item results are listed below.',
  'The local service did not return per-item results.': 'The local service did not return per-item results.',
  '· Organise files': '· Organise files',
  'Organisation workflow': 'Organisation workflow',
  'Review and adjust': 'Review and adjust',
  'Create copies': 'Create copies',
  'Save the recipe': 'Save the recipe',
  'Confirm the names, then organise the whole batch': 'Confirm the names, then organise the whole batch',
  'files — start with three samples of different types': 'files — start with three samples of different types',
  'This is a preview of the real plan. Edit destinations here; copies are created in a new output folder only after you confirm.': 'This is a preview of the real plan. Edit destinations here; copies are created in a new output folder only after you confirm.',
  'How this page works': 'How this page works',
  'This page organises by a declarative rule plus your per-file edits.': 'This page organises by a declarative rule plus your per-file edits.',
  'A single edit is not treated as a learned rule; every proposal is confirmed before any copy is created.': 'A single edit is not treated as a learned rule; every proposal is confirmed before any copy is created.',
  'Three samples of different types': 'Three samples of different types',
  'Edit, press “Update preview”, then check the full batch.': 'Edit, press “Update preview”, then check the full batch.',
  'Nothing written yet': 'Nothing written yet',
  'Expand': 'Expand',
  'Source': 'Source',
  'Ready to create the copies?': 'Ready to create the copies?',
  'Copies are created only in the new output folder. Originals stay exactly as they are.': 'Copies are created only in the new output folder. Originals stay exactly as they are.',
  'Keep this recipe': 'Keep this recipe',
  'Save the versioned rule and this batch\'s edits. Loading it later starts from a fresh preview.': 'Save the versioned rule and this batch\'s edits. Loading it later starts from a fresh preview.',
  'For example: 2026 client files': 'For example: 2026 client files',
  'Loading saved recipes…': 'Loading saved recipes…',
  'No saved recipes yet.': 'No saved recipes yet.',
  'Check the evidence or the specification content.': 'Check the evidence or the specification content.',
  'Unsaved name edits': 'Unsaved name edits',
  'The local service did not complete the request. Try again.': 'The local service did not complete the request. Try again.',
  'Could not reload the latest preview.': 'Could not reload the latest preview.',
  'The local service did not return a usable preview.': 'The local service did not return a usable preview.',
  'The local service did not report the actual status of this file.': 'The local service did not report the actual status of this file.',
  'These results come from the actual local writes. If something needs attention, create a new preview; a changed source also needs a fresh snapshot.': 'These results come from the actual local writes. If something needs attention, create a new preview; a changed source also needs a fresh snapshot.',
  'Saved recipes cannot be read right now.': 'Saved recipes cannot be read right now.',
  'Preview updated. Check the full batch again.': 'Preview updated. Check the full batch again.',
  'Update the preview before creating copies.': 'Update the preview before creating copies.',
  'Finished; some files need attention.': 'Finished; some files need attention.',
  'All organised copies were created.': 'All organised copies were created.',
  'Recipe saved. Load it next time to build a new preview.': 'Recipe saved. Load it next time to build a new preview.',
  'Load recipe': 'Load recipe',
  'Update or clear your name edits before loading another recipe.': 'Update or clear your name edits before loading another recipe.',
  'The local service did not return a new preview.': 'The local service did not return a new preview.',
  'Recipe loaded and a new preview was created.': 'Recipe loaded and a new preview was created.',
} as const

export type UiStringKey = keyof typeof en

const zhTW: Record<UiStringKey, string> = {
  'Ditto · Organise files': 'Ditto · 整理檔案',
  'Ditto · Code → Spec': 'Ditto · 程式碼 → 規格',
  'Skip to content': '跳至主要內容',
  'Local review page': '本機檢閱頁面',
  'Synthetic demo · deterministic generator, no model calls': '合成示範 · 確定性產生器，不呼叫模型',
  'Review a few. Ditto the rest.': '檢閱少數，其餘交給 Ditto。',
  '· Review a few. Ditto the rest.': '· 檢閱少數，其餘交給 Ditto。',
  'Choose samples': '選擇範例',
  'Review': '檢閱',
  'Preview all': '預覽全部',
  'Apply': '套用',
  'Discover': '探索',
  'Review 3 samples': '檢閱 3 個範例',
  'Preview everything': '預覽全部',
  'Review the proposed file locations': '檢閱建議的檔案位置',
  'Check three representative files, then inspect the complete batch before any copies are created. Originals are never moved or changed.': '先檢查三個代表性檔案，再於建立副本前檢閱完整批次。原始檔案絕不會被移動或變更。',
  'Review digest': '檢閱摘要',
  'Local-only review': '僅限本機檢閱',
  'This page talks only to the loopback service that opened it. It loads no remote scripts, fonts, or analytics.': '此頁面只會連線至開啟它的本機服務，不載入遠端指令碼、字型或分析工具。',
  'Representative samples': '代表性範例',
  'Edit a proposed location if needed. Changes rebuild the whole preview before apply.': '如有需要，可編輯建議位置。變更會在套用前重建完整預覽。',
  'Three deterministic samples': '三個確定性範例',
  'Original file': '原始檔案',
  'Organised location': '整理後位置',
  'A path relative to the output folder. The original file is never moved.': '相對於輸出資料夾的路徑。原始檔案絕不會被移動。',
  'No files to organise in this folder': '此資料夾中沒有可整理的檔案',
  'Choose a source folder that contains files, then create a new preview.': '請選擇包含檔案的來源資料夾，然後建立新的預覽。',
  'No files to show.': '沒有可顯示的檔案。',
  'files': '個檔案',
  'Update preview': '更新預覽',
  'No unsaved location changes': '沒有未儲存的位置變更',
  'Unsaved location changes': '有未儲存的位置變更',
  'This batch': '此批次',
  'Source files': '來源檔案',
  'Ready to copy': '可建立副本',
  'Need attention': '需要處理',
  'Source folder': '來源資料夾',
  'New output folder': '新輸出資料夾',
  'Before creating copies': '建立副本前',
  'Only the reviewed destinations are created. Existing files are never overwritten.': '只會建立已檢閱的目的地，絕不覆寫現有檔案。',
  'Create organised copies': '建立整理後的副本',
  'Full batch': '完整批次',
  'Actual copy results': '實際複製結果',
  'Saved recipes': '已儲存的配方',
  'Save this reviewed rule for another batch. Loading a recipe always creates a new preview.': '儲存此已檢閱規則供其他批次使用。載入配方一律會建立新預覽。',
  'Recipe name': '配方名稱',
  'Save recipe': '儲存配方',
  'Waiting': '等待中',
  'Copying': '複製中',
  'Copied': '已複製',
  'Needs a fix': '需要修正',
  'Failed': '失敗',
  'Needs review': '需要檢閱',
  'Unknown result': '未知結果',
  'Enter the organised location.': '請輸入整理後的位置。',
  'Use a path relative to the output folder.': '請使用相對於輸出資料夾的路徑。',
  'The location cannot leave the output folder.': '位置不得離開輸出資料夾。',
  'Updating…': '更新中…',
  'Creating copies…': '正在建立副本…',
  'Saving…': '儲存中…',
  'Loading…': '載入中…',
  'Code-to-spec workflow': '程式碼轉規格工作流程',
  'Code → Markdown specifications': '程式碼 → Markdown 規格',
  'Calibrate three samples, then ditto the rest': '校準三個範例，再處理其餘項目',
  'Your source is never executed or modified. Every fact in a specification cites source lines; anything unsupported is collected under “Needs confirmation”.': '來源程式碼絕不會被執行或修改。規格中的每項事實都會引用來源行；無法佐證的內容會列於「需要確認」。',
  'Three structurally different samples': '三個結構不同的範例',
  'Edit the Markdown and the batch instructions directly; updates change the review digest.': '直接編輯 Markdown 與批次指示；更新後會變更檢閱摘要。',
  'Samples approved — the full batch can be generated.': '範例已核准 — 現在可產生完整批次。',
  'Samples not approved yet — full batch locked.': '範例尚未核准 — 完整批次仍鎖定。',
  'Batch instructions (optional)': '批次指示（選填）',
  'For example: list inputs, outputs, and observable errors first; keep each bullet under 25 words.': '例如：先列出輸入、輸出及可觀察的錯誤；每個項目不超過 25 個字。',
  'Instructions only guide the text of this batch. They cannot run code or commands.': '指示只會引導此批次的文字，無法執行程式碼或命令。',
  'Update samples': '更新範例',
  'Approve the three samples': '核准三個範例',
  'Generate the full batch': '產生完整批次',
  'Full batch preview': '完整批次預覽',
  'Full batch preview (': '完整批次預覽（',
  'modules)': ' 個模組）',
  'modules': '個模組',
  'Per-item write results': '逐項寫入結果',
  'This scan': '本次掃描',
  'Modules discovered': '探索到的模組',
  'Specifications generated': '已產生的規格',
  'Need confirmation': '需要確認',
  'Excluded': '已排除',
  'New specification output folder': '新規格輸出資料夾',
  'Needs confirmation': '需要確認',
  'Nothing needs confirmation right now.': '目前沒有需要確認的項目。',
  'Excluded from the scan': '已從掃描中排除',
  'Nothing was excluded.': '沒有排除任何項目。',
  'Before writing': '寫入前',
  'Only a complete preview whose samples are approved and whose source snapshot is unchanged can be written. Nothing is written before you press the button.': '只有範例已核准、來源快照未變更的完整預覽才能寫入。按下按鈕前不會寫入任何內容。',
  'Write the approved specifications': '寫入已核准的規格',
  'Sample · review': '範例 · 檢閱',
  'Approved': '已核准',
  'Ready to write': '可寫入',
  'Generated': '已產生',
  'Written': '已寫入',
  'Skipped': '已略過',
  'Rejected': '已拒絕',
  'Editable Markdown specification': '可編輯的 Markdown 規格',
  'Markdown specification preview': 'Markdown 規格預覽',
  'Not generated yet.': '尚未產生。',
  'No evidence linked back to the source yet.': '尚無連回來源的證據。',
  'Unsaved sample or instruction edits — update the samples first.': '範例或指示有未儲存的編輯 — 請先更新範例。',
  'Updating samples…': '正在更新範例…',
  'Recording approval…': '正在記錄核准…',
  'Generating the full batch…': '正在產生完整批次…',
  'Writing Markdown…': '正在寫入 Markdown…',
  'Sample': '範例',
  'Edit, then press “Update samples”. Every change produces a new review digest.': '編輯後按下「更新範例」。每項變更都會產生新的檢閱摘要。',
  'Source evidence': '來源證據',
  'No modules available as samples.': '沒有可作為範例的模組。',
  'No modules discovered.': '未探索到任何模組。',
  'The scan did not report exclusion details.': '掃描未提供排除項目的詳細資料。',
  'Samples updated. Review and approve the three specifications again.': '範例已更新。請重新檢閱並核准三份規格。',
  'Update the samples before approving them.': '請先更新範例再進行核准。',
  'Three samples approved. You can generate the full batch now.': '三個範例已核准。現在可以產生完整批次。',
  'The local service did not confirm the approval.': '本機服務未確認核准。',
  'Full batch generated. Resolve anything under “Needs confirmation”, then write the specifications.': '完整批次已產生。請先處理「需要確認」中的項目，再寫入規格。',
  'Write complete. Per-item results are listed below.': '寫入完成。逐項結果如下。',
  'The local service did not return per-item results.': '本機服務未傳回逐項結果。',
  '· Organise files': '· 整理檔案',
  'Organisation workflow': '檔案整理工作流程',
  'Review and adjust': '檢閱與調整',
  'Create copies': '建立副本',
  'Save the recipe': '儲存配方',
  'Confirm the names, then organise the whole batch': '確認名稱，再整理整個批次',
  'files — start with three samples of different types': '個檔案 — 先檢閱三個不同類型的範例',
  'This is a preview of the real plan. Edit destinations here; copies are created in a new output folder only after you confirm.': '這是實際計畫的預覽。請在此編輯目的地；只有在確認後，才會於新的輸出資料夾建立副本。',
  'How this page works': '此頁面的運作方式',
  'This page organises by a declarative rule plus your per-file edits.': '此頁面依據宣告式規則及您對個別檔案的編輯進行整理。',
  'A single edit is not treated as a learned rule; every proposal is confirmed before any copy is created.': '單一編輯不會被視為已學習的規則；建立任何副本前，都會確認每項建議。',
  'Three samples of different types': '三個不同類型的範例',
  'Edit, press “Update preview”, then check the full batch.': '編輯後按下「更新預覽」，再檢查完整批次。',
  'Nothing written yet': '尚未寫入任何內容',
  'Expand': '展開',
  'Source': '來源',
  'Ready to create the copies?': '準備建立副本了嗎？',
  'Copies are created only in the new output folder. Originals stay exactly as they are.': '副本只會建立於新的輸出資料夾中。原始檔案會維持原狀。',
  'Keep this recipe': '保留此配方',
  'Save the versioned rule and this batch\'s edits. Loading it later starts from a fresh preview.': '儲存具版本的規則及此批次的編輯。日後載入時會從全新預覽開始。',
  'For example: 2026 client files': '例如：2026 客戶檔案',
  'Loading saved recipes…': '正在載入已儲存的配方…',
  'No saved recipes yet.': '尚未儲存任何配方。',
  'Check the evidence or the specification content.': '請檢查證據或規格內容。',
  'Unsaved name edits': '有未儲存的名稱編輯',
  'The local service did not complete the request. Try again.': '本機服務未完成要求，請再試一次。',
  'Could not reload the latest preview.': '無法重新載入最新預覽。',
  'The local service did not return a usable preview.': '本機服務未傳回可用的預覽。',
  'The local service did not report the actual status of this file.': '本機服務未回報此檔案的實際狀態。',
  'These results come from the actual local writes. If something needs attention, create a new preview; a changed source also needs a fresh snapshot.': '這些結果來自實際的本機寫入。若有項目需要處理，請建立新預覽；來源變更後也需要新的快照。',
  'Saved recipes cannot be read right now.': '目前無法讀取已儲存的配方。',
  'Preview updated. Check the full batch again.': '預覽已更新。請重新檢查完整批次。',
  'Update the preview before creating copies.': '建立副本前請先更新預覽。',
  'Finished; some files need attention.': '已完成；部分檔案需要處理。',
  'All organised copies were created.': '所有整理後的副本均已建立。',
  'Recipe saved. Load it next time to build a new preview.': '配方已儲存。下次載入即可建立新預覽。',
  'Load recipe': '載入配方',
  'Update or clear your name edits before loading another recipe.': '載入另一個配方前，請更新或清除名稱編輯。',
  'The local service did not return a new preview.': '本機服務未傳回新預覽。',
  'Recipe loaded and a new preview was created.': '配方已載入，並已建立新預覽。',
}

export const uiStrings: Record<UiLocale, Record<UiStringKey, string>> = { en, 'zh-TW': zhTW }

export function isUiLocale(value: string | undefined): value is UiLocale {
  return supportedUiLocales.includes(value as UiLocale)
}
